### ISSUE TITLE
boot completed with black screen 

### ISSUE THREAD

**Issue by DarkCamper242** [AOSP-ha3g/device_samsung_ha3g#1]
dude do you know the solution for black screen after boot complete ?

**Comment by MIUI56** [comment]
Yeah remove support sepolicy for now

**Comment by MIUI56** [comment]
Don't use cpu boot demon

**Comment by MIUI56** [comment]
Make clean 
And build again

**Comment by DarkCamper242** [comment]
okay add libexynosdisplay package solved problem
